version: '3.7'

volumes:
    ocbr_database:
    ocbr_storage:

networks:
    ocbr_network:

services:
    ocbr:
        container_name: opencartbrasil
        build:
          context: .docker
          dockerfile: Dockerfile
          args:
            VERSION: "1.x"
        ports:
            - 8080:80
        environment:
            - DB_HOSTNAME=ocbr_db
            - DB_USERNAME=store
            - DB_PASSWORD=store
            - DB_DATABASE=opencartbrasil
            - USERNAME=admin
            - PASSWORD=admin
            - HTTP_SERVER=http://localhost:8080/
            - PUID=1000
            - PGID=1000
        networks:
            - ocbr_network
        volumes:
            - ./:/var/www/html
            - ocbr_storage:/var/www/storage
        depends_on:
            - ocbr_db
        command: |
            bash -c "
            mkdir -p /var/www/storage/cache &&
            mkdir -p /var/www/storage/logs &&
            usermod -u 1000 www-data &&
            groupmod -g 1000 www-data &&
            chown -R www-data:www-data /var/www/html /var/www/storage &&
            chmod -R 775 /var/www/html /var/www/storage &&
            apache2-foreground
            "

    ocbr_db:
        image: mysql:5.7
        container_name: opencartbrasil_db
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_USER=store
            - MYSQL_PASSWORD=store
            - MYSQL_DATABASE=opencartbrasil
        networks:
            - ocbr_network
        volumes:
            - ocbr_database:/var/lib/mysql